apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: simple-monitoring
  namespace: default
spec:
  selector:
    matchLabels:
      app: monitoring-agent
  template:
    metadata:
      labels:
        app: monitoring-agent
    spec:
      #nodeSelector: Pode ser usado para rodar em nós específicos!
       # gpu: true
      containers:
      - name: monitoring-agent
        image: busybox:latest
        command: ["/bin/sh", "-c", "while true; do echo 'Monitorando nó'; sleep 300; done"]
        resources:
          limits:
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 20Mi
