apiVersion: v1
kind: Service
metadata:
  name: meu-servico-clusterip
  labels:
    app: minha-aplicacao
spec:
  type: ClusterIP
  ports:
  - port: 80        # porta exposta pelo serviço
    targetPort: 80  # porta no pod destino
    protocol: TCP
    name: http
  selector:
    app: minha-aplicacao  # seleciona os pods com esta etiqueta
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    app: minha-aplicacao
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minha-aplicacao
  template:
    metadata:
      labels:
        app: minha-aplicacao
    spec:
      initContainers: # Usado apenas para criar HTML específico para o nginx
      - name: init-html
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "<!DOCTYPE html>
            <html>
            <head>
              <meta charset=\"UTF-8\">
              <title>Informações do Pod</title>
              <style>
                body {
                  font-family: Arial, sans-serif;
                  margin: 0;
                  padding: 30px;
                  background-color: #f5f5f5;
                }
                .container {
                  background-color: white;
                  border-radius: 8px;
                  padding: 20px;
                  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
                  max-width: 600px;
                  margin: 0 auto;
                }
                h1 {
                  color: #333;
                }
                .info {
                  margin: 20px 0;
                  padding: 15px;
                  background-color: #e6f7ff;
                  border-radius: 4px;
                }
              </style>
            </head>
            <body>
              <div class=\"container\">
                <h1>Informações do Pod Nginx</h1>
                <div class=\"info\">
                  <p><strong>Nome do Pod:</strong> ${POD_NAME}</p>
                  <p><strong>IP do Pod:</strong> ${POD_IP}</p>
                  <p><strong>Hostname:</strong> $(hostname)</p>
                  <p><strong>Data e Hora da Inicialização:</strong> $(date)</p>
                </div>
              </div>
            </body>
            </html>" > /usr/share/nginx/html/index.html
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        emptyDir: {}
