apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: multi-container-demo
spec:
  containers:
  - name: container-web
    image: nginx:1.21
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
      
  - name: container-logger
    image: busybox:1.36
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          log_msg="Log do sistema atualizado em $(date)";
          echo "$log_msg" >> /data/log.txt;
          echo "$log_msg";
          sleep 10;
        done
    volumeMounts:
    - name: shared-data
      mountPath: /data
      
  - name: container-monitor
    image: busybox:1.36
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          monitor_msg="Verificando estado dos containers em $(date)";
          echo "$monitor_msg" >> /data/monitor.txt;
          echo "$monitor_msg";
          sleep 30;
        done
    volumeMounts:
    - name: shared-data
      mountPath: /data
      
  volumes:
  - name: shared-data
    emptyDir: {} 