apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: servidor-web
  name: servidor-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servidor-web
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: servidor-web
    spec:
      containers:
      - image: nginx
        name: nginx
