apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq-consumer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rabbitmq-consumer
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: rabbitmq-consumer
          image: rabbitmq-consumer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: host
            - name: EXCHANGE_NAME
              value: "order-events"
            - name: EXCHANGE_TYPE
              value: "topic"
            - name: QUEUE_NAME
              value: "order-processor"
            - name: ROUTING_KEY
              value: "#"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
